[project]
site_name = "Hardwood Heuristics"
site_description = "Empirical analysis of NBA folk wisdom"
site_author = "Hardwood Heuristics Team"
site_url = "https://tomasortega.github.io/Hardwood-Heuristics/"

repo_name = "TomasOrtega/Hardwood-Heuristics"
repo_url = "https://github.com/TomasOrtega/Hardwood-Heuristics"

extra_javascript = [
  "https://polyfill.io/v3/polyfill.min.js?features=es6",
  "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js",
]

[project.theme]
variant = "classic"
language = "en"
logo = "assets/logo/site_icon.svg"
favicon = "assets/logo/site_icon.svg"
features = [
  # "navigation.tabs",
  "search.highlight",
  "content.code.copy",
  "navigation.instant",
  "navigation.tracking",
  "navigation.footer"
]

[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "orange"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Roboto"
code = "Roboto Mono"
